 ## numpy packages

In [3]:
import numpy as np


In [5]:
# 1D array
a=np.array([1,2,3,4,5])
print(a.ndim) ### dimension

1


In [39]:
## 2d array
a1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a1
a1.ndim


2

In [10]:
a1.shape

(3, 3)

In [15]:
## dynamic insertion
a3=np.array([],dtype="int32")

In [17]:
a3=np.append(a3,int(input()))
a3

12


array([12])

In [18]:
a3=np.append(a3,[23,34,45,56,67])## userdefined elements
a3

array([12, 23, 34, 45, 56, 67])

## slicing


In [20]:
print(a3[3])

45


In [25]:
print(a1[1,1])

5


In [27]:
print(a1[2:,:])

[[7 8 9]]


In [29]:
print(a1[2:,0:2])

[[7 8]]


In [32]:
print(a1[0,0:2])

[1 2]


In [33]:
print(a1[:,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(a1[0::2,1])

[2 8]


In [36]:
print(a1[0::2,0])

[1 7]


In [37]:
print(a1[0::2,:])

[[1 2 3]
 [7 8 9]]


In [40]:
for row in a1:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [43]:
list1=[[2,1],[3,4]]
for i in list1:
    print(i)

[2, 1]
[3, 4]


In [46]:
for ele in a1.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [47]:
np.array(a1.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### indexing with boolean array

In [49]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [51]:
result=(arr1%2==0)
result


array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [52]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))## vertical stacking


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [58]:
print(np.hstack((arr1,arr2)))## horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


## attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape



In [59]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
print(arr.size)
print(arr.itemsize)## int
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### functions;
1. zeroes
2. ones
3. full
4. eye

In [64]:
z=np.zeros((2,3),dtype="int32")## default type if float
z

array([[0, 0, 0],
       [0, 0, 0]])

In [66]:
o= np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
f= np.full((2,2),"abc")
f

array([['abc', 'abc'],
       ['abc', 'abc']], dtype='<U3')

In [70]:
#eye() all diagonal elements are one-->"identical matrix"
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [74]:
# linspace()--> linear spacing elements
l=np.linspace(1,10,5)## divides elements from starting to ending range into 5 equal parts
l


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [80]:
a=np.arange(1,11,2)# start,stop,step
a

array([1, 3, 5, 7, 9])

In [82]:
#ravel
print(np.array(a.flat))
print(a.ravel())

[1 3 5 7 9]
[1 3 5 7 9]


In [90]:
print(a1.sum())
print(a1.sum(axis=1))
print(a1.sum(axis=0))

78
[ 6 15 24 33]
[22 26 30]


In [92]:
print(a.min())
print(a.max())

1
11


In [93]:
np.median(a)

6.0

In [94]:
np.mean(a)

6.0

In [95]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479])

### mathematical operators: ``+,-,*,/,%``

In [96]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)


[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


## dot()--->matrix muliplication

In [97]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [98]:
## array transpose
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## applying user defined function:


In [99]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [101]:
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [105]:
f=np.vectorize(lambda x: x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [104]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])