In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

82
0.9445114553241007


In [4]:
#print array wiht random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[71 37 56]
[[ 9 33 33 90]
 [25 97 37 61]
 [40 31 93 23]]
[[[ 1 33]
  [11 51]
  [34 78]
  [41 26]]

 [[23 50]
  [54 90]
  [29  5]
  [81  6]]

 [[26 92]
  [94 52]
  [84 26]
  [69  2]]]


In [5]:
print(random.rand())# gives single value
print(random.rand(3))# gives 1d array
print(random.rand(2,3))#gives 2d array

0.18891868390741107
[0.82943737 0.48119912 0.47977324]
[[0.08414202 0.41645709 0.71189484]
 [0.0274047  0.28300886 0.29211929]]


In [6]:
a=random.randint(100,size=(3,2)).ravel()
a


array([ 0, 80, 39,  7, 68, 78])

In [7]:
random.choice(a)

39

In [8]:
random.choice([1,2,3,4,5],size=(3,4))

array([[3, 5, 3, 2],
       [1, 5, 4, 2],
       [2, 4, 2, 2]])

### pandas
1. data manipulation,analysis and cleaning
2. tabular data,unlabelled data
3.  ```DATA FRAMES: collection of rows and columns```


## creating a dataframe using dictionaies


In [11]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'f':9}
data={"first":dict1,"second":dict2}
df=pd.DataFrame(data)#-->NaN not a number
df## better not use print function


first  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [16]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}## keys should match
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"first":dict1,"second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [18]:
 #1.simple dictionary-->Dataframe length should match
d1={"name":['a','b','c','d'],"address":['w','x','y','z']}
df1=pd.DataFrame(d1)
df1

name address
0    a       w
1    b       x
2    c       y
3    d       z

In [24]:
# using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.5,67.4,23.34,46.87,87.9,65.6,98.7])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={'column1':s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3


column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    23.34       f
6        7    46.87       g
7        8    87.90       h
8        9    65.60       i
9       10    98.70       j

In [31]:
# extract data from data frame
df3[["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    23.34
6        7    46.87
7        8    87.90
8        9    65.60
9       10    98.70

## selecting data from dataframe
1. loc
2. iloc

In [32]:
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [33]:
df3.loc[:,:]

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    23.34       f
6        7    46.87       g
7        8    87.90       h
8        9    65.60       i
9       10    98.70       j

In [35]:
df3.loc[:,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    23.34
6        7    46.87
7        8    87.90
8        9    65.60
9       10    98.70

In [36]:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    23.34

In [37]:
type(df3)

pandas.core.frame.DataFrame

In [38]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

In [39]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

1. ````loc- row and columns````



2. ````iloc row and column index values````

### retrieving the info of DataFrame


In [40]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [42]:
df3.shape

(10, 3)

In [43]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [44]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [45]:
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [46]:
df.tail(2)

first  second
d      4       8
e      5       9

In [47]:
df3.tail()

column1  column2 column3
5        6    23.34       f
6        7    46.87       g
7        8    87.90       h
8        9    65.60       i
9       10    98.70       j

In [48]:
df3.sample()

column1  column2 column3
2        3     45.3       c

In [49]:
df3.sample(2)

column1  column2 column3
6        7    46.87       g
1        2    23.34       b

In [50]:
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9